# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID
# Use a package of configuration called an orb.
jobs:
  print_pipeline_id_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
  # Declare a dependency on the welcome-orb
  
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print_pipeline_id_job
